# Generated by Django 3.1.6 on 2021-05-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210502_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='Date_Created',
            new_name='date_Created',
        ),
    ]
